CREATE TABLE IF NOT EXISTS PARTICIPANTE(
    IDEN NUMERIC(10) DEFAULT 1,
    NOME VARCHAR(150) NOT NULL,
    IDADE NUMERIC(10) DEFAULT 1,
    EMAIL VARCHAR(30) NOT NULL,
    NUMERO NUMERIC(12) DEFAULT 1,

    PRIMARY KEY(IDEN)
);
CREATE TABLE IF NOT EXISTS RESPONSAVEL(

    IDENRESPON NUMERIC(10) DEFAULT 1,

    PRIMARY KEY(IDENRESPON)
);
CREATE TABLE IF NOT EXISTS  BARRACAS(
    IDEN NUMERIC(10) DEFAULT 1,
    NOME VARCHAR(30) NOT NULL,
    PRODUTO VARCHAR(30) NOT NULL,
    LOCALIZACAO VARCHAR(30) NOT NULL,
    IDENRESPON NUMERIC(10) DEFAULT 1,

    PRIMARY    KEY(IDEN),
    FOREIGN KEY(IDENRESPON) REFERENCES RESPONSAVEL(IDENRESPON)
);
CREATE TABLE IF NOT EXISTS ATIVIDADE(
    NOME VARCHAR(30) NOT NULL,
    HORA_INICIO TIME,
    HORA_TERMINO TIME,
    DESCRICAO VARCHAR(100) NOT NULL,
    IDEN NUMERIC(10) DEFAULT 1,

    PRIMARY KEY(NOME),
    FOREIGN KEY(IDEN) REFERENCES PARTICIPANTE(IDEN)
);
